// Mocks generated by Mockito 5.4.4 from annotations
// in my_movie/test/presentation/pages/tv/tv_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:core/utils/state_enum.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:my_movie/domain/entity/tv/tv.dart' as _i10;
import 'package:my_movie/domain/entity/tv/tv_detail.dart' as _i7;
import 'package:my_movie/domain/usecases/tv/get_tv_detail.dart' as _i2;
import 'package:my_movie/domain/usecases/tv/get_tv_recommendations.dart' as _i3;
import 'package:my_movie/domain/usecases/tv/get_tv_watchlist_status.dart'
    as _i4;
import 'package:my_movie/domain/usecases/tv/remove_tv_watchlist.dart' as _i6;
import 'package:my_movie/domain/usecases/tv/save_tv_watchlist.dart' as _i5;
import 'package:my_movie/presentation/providers/tv/tv_detail_notifier.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvDetail_0 extends _i1.SmartFake implements _i2.GetTvDetail {
  _FakeGetTvDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTvRecommendations {
  _FakeGetTvRecommendations_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvWatchlistStatus_2 extends _i1.SmartFake
    implements _i4.GetTvWatchlistStatus {
  _FakeGetTvWatchlistStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveTvWatchlist_3 extends _i1.SmartFake
    implements _i5.SaveTvWatchlist {
  _FakeSaveTvWatchlist_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveTvWatchlist_4 extends _i1.SmartFake
    implements _i6.RemoveTvWatchlist {
  _FakeRemoveTvWatchlist_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvDetail_5 extends _i1.SmartFake implements _i7.TvDetail {
  _FakeTvDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailNotifier extends _i1.Mock implements _i8.TvDetailNotifier {
  MockTvDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvDetail get useCaseGetTvDetail => (super.noSuchMethod(
        Invocation.getter(#useCaseGetTvDetail),
        returnValue: _FakeGetTvDetail_0(
          this,
          Invocation.getter(#useCaseGetTvDetail),
        ),
      ) as _i2.GetTvDetail);

  @override
  _i3.GetTvRecommendations get useCaseGetTvRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#useCaseGetTvRecommendations),
        returnValue: _FakeGetTvRecommendations_1(
          this,
          Invocation.getter(#useCaseGetTvRecommendations),
        ),
      ) as _i3.GetTvRecommendations);

  @override
  _i4.GetTvWatchlistStatus get useCaseGetTvWatchlistStatus =>
      (super.noSuchMethod(
        Invocation.getter(#useCaseGetTvWatchlistStatus),
        returnValue: _FakeGetTvWatchlistStatus_2(
          this,
          Invocation.getter(#useCaseGetTvWatchlistStatus),
        ),
      ) as _i4.GetTvWatchlistStatus);

  @override
  _i5.SaveTvWatchlist get useCaseSaveWatchlist => (super.noSuchMethod(
        Invocation.getter(#useCaseSaveWatchlist),
        returnValue: _FakeSaveTvWatchlist_3(
          this,
          Invocation.getter(#useCaseSaveWatchlist),
        ),
      ) as _i5.SaveTvWatchlist);

  @override
  _i6.RemoveTvWatchlist get useCaseRemoveWatchlist => (super.noSuchMethod(
        Invocation.getter(#useCaseRemoveWatchlist),
        returnValue: _FakeRemoveTvWatchlist_4(
          this,
          Invocation.getter(#useCaseRemoveWatchlist),
        ),
      ) as _i6.RemoveTvWatchlist);

  @override
  _i7.TvDetail get tvDetail => (super.noSuchMethod(
        Invocation.getter(#tvDetail),
        returnValue: _FakeTvDetail_5(
          this,
          Invocation.getter(#tvDetail),
        ),
      ) as _i7.TvDetail);

  @override
  _i9.RequestState get tvDetailState => (super.noSuchMethod(
        Invocation.getter(#tvDetailState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);

  @override
  List<_i10.Tv> get tvRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvRecommendations),
        returnValue: <_i10.Tv>[],
      ) as List<_i10.Tv>);

  @override
  _i9.RequestState get tvRecommendationsState => (super.noSuchMethod(
        Invocation.getter(#tvRecommendationsState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#watchlistMessage),
        ),
      ) as String);

  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> fetchTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvDetail,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> addWatchlist(_i7.TvDetail? tv) => (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tv],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> removeFromWatchlist(_i7.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tv],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
