// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOWxpeey8ygiMQfJpjC0wfJVqYpZi243A',
    appId: '1:335478987548:web:4d2c2a5adda1f8d43e78d9',
    messagingSenderId: '335478987548',
    projectId: 'ditonton-e222a',
    authDomain: 'ditonton-e222a.firebaseapp.com',
    storageBucket: 'ditonton-e222a.firebasestorage.app',
    measurementId: 'G-0KLLGZF6K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOO_tPgL9Ox9tmRacE_BgQyq1X-7Ieok4',
    appId: '1:335478987548:android:07565e18ffea8ad93e78d9',
    messagingSenderId: '335478987548',
    projectId: 'ditonton-e222a',
    storageBucket: 'ditonton-e222a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIekQbPf3gr-QkCvWQunCuCuuoXPmlbbI',
    appId: '1:335478987548:ios:7541a21c4a09fd443e78d9',
    messagingSenderId: '335478987548',
    projectId: 'ditonton-e222a',
    storageBucket: 'ditonton-e222a.firebasestorage.app',
    iosBundleId: 'com.example.myMovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOWxpeey8ygiMQfJpjC0wfJVqYpZi243A',
    appId: '1:335478987548:web:8d8f466f09eae0283e78d9',
    messagingSenderId: '335478987548',
    projectId: 'ditonton-e222a',
    authDomain: 'ditonton-e222a.firebaseapp.com',
    storageBucket: 'ditonton-e222a.firebasestorage.app',
    measurementId: 'G-PFVCKLWT1Z',
  );
}
